package br.com.threadtec.lbb.bancodados;
// Generated May 2, 2013 6:37:11 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Lote generated by hbm2java
 */
@Entity
@Table(name="lote",schema="public")
@NamedQueries({@NamedQuery(name="Lote.buscar_lote_id",          query="FROM Lote WHERE id = :_id"),
               @NamedQuery(name="Lote.buscar_lote_notafiscal",  query="FROM Lote WHERE notaFiscal = :_nf"),
               @NamedQuery(name="Lote.buscar_lote_numero",      query="FROM Lote WHERE numero = :_numero"),
               @NamedQuery(name="Lote.buscar_lote_validade",    query="FROM Lote WHERE validade = :_validade"),
               @NamedQuery(name="Lote.buscar_lote_todos",       query="FROM Lote")})
public class Lote  implements java.io.Serializable {

     public static final String BUSCAR_ID             = "Lote.buscar_lote_id";
     public static final String BUSCAR_NOTAFISCAL     = "Lote.buscar_lote_notafiscal";
     public static final String BUSCAR_NUMERO         = "Lote.buscar_lote_numero";
     public static final String BUSCAR_VALIDADE       = "Lote.buscar_lote_validade";
     public static final String BUSCAR_TODOS          = "Lote.buscar_lote_todos";
     
     @Id
     @GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "lote_sequence")
     @SequenceGenerator(name="lote_sequence", sequenceName = "lote_sequence", allocationSize=1)
     private int id;
     @ManyToOne
     @JoinColumn(name = "id", referencedColumnName = "id", insertable=false, updatable=false) 
     private NotaFiscal notaFiscal;
     @Column(name="numero", nullable=false)
     private int numero;
     @Temporal(TemporalType.TIMESTAMP)
     @Column(name="validade", nullable=false, length=29)
     private Date validade;

    public Lote() {
    }

    public Lote(int id, NotaFiscal notaFiscal, int numero, Date validade) {
       this.id = id;
       this.notaFiscal = notaFiscal;
       this.numero = numero;
       this.validade = validade;
    }
   
        public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
        public NotaFiscal getNotaFiscal() {
        return this.notaFiscal;
    }
    
    public void setNotaFiscal(NotaFiscal notaFiscal) {
        this.notaFiscal = notaFiscal;
    }
    
        public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
        public Date getValidade() {
        return this.validade;
    }
    
    public void setValidade(Date validade) {
        this.validade = validade;
    }




}


