package br.com.threadtec.lbb.bancodados;
// Generated May 2, 2013 6:37:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * NotaFiscal generated by hbm2java
 */
@Entity
@Table(name="nota_fiscal",schema="public")
@NamedQueries({@NamedQuery(name="NotaFiscal.buscar_notafiscal_id",          query="FROM NotaFiscal WHERE id = :_id"),
               @NamedQuery(name="NotaFiscal.buscar_notafiscal_idLote",      query="FROM NotaFiscal WHERE indicadorLote = :_indicadorLote"),
               @NamedQuery(name="NotaFiscal.buscar_notafiscal_todos",       query="FROM NotaFiscal")})
public class NotaFiscal  implements java.io.Serializable {

     public static final String BUSCAR_ID             = "NotaFiscal.buscar_notafiscal_id";
     public static final String BUSCAR_IDLOTE         = "NotaFiscal.buscar_notafiscal_idLote";
     public static final String BUSCAR_TODOS          = "NotaFiscal.buscar_notafiscal_todos";

     @Id
     @GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "nota_fiscal_sequence")
     @SequenceGenerator(name="nota_fiscal_sequence", sequenceName = "nota_fiscal_sequence", allocationSize=1)
     private int id;
     @ManyToOne
     @JoinColumn(name = "id", referencedColumnName = "id", insertable=false, updatable=false) 
     private Fornecedor fornecedor;
     @Column(name="indicador_lote", nullable=false)
     private int indicadorLote;
     @OneToMany(mappedBy="notaFiscal", cascade=CascadeType.ALL, fetch=FetchType.LAZY, targetEntity=Estoque.class) 
     private Set estoques = new HashSet(0);
     @OneToMany(mappedBy="notaFiscal", cascade=CascadeType.ALL, fetch=FetchType.LAZY, targetEntity=Lote.class) 
     private Set lotes = new HashSet(0);

    public NotaFiscal() {}

	
    public NotaFiscal(int id, Fornecedor fornecedor, int indicadorLote) {
        this.id = id;
        this.fornecedor = fornecedor;
        this.indicadorLote = indicadorLote;
    }
    public NotaFiscal(int id, Fornecedor fornecedor, int indicadorLote, Set estoques, Set lotes) {
       this.id = id;
       this.fornecedor = fornecedor;
       this.indicadorLote = indicadorLote;
       this.estoques = estoques;
       this.lotes = lotes;
    }
   
         public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
        public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }
    
        public int getIndicadorLote() {
        return this.indicadorLote;
    }
    
    public void setIndicadorLote(int indicadorLote) {
        this.indicadorLote = indicadorLote;
    }
    
        public Set getEstoques() {
        return this.estoques;
    }
    
    public void setEstoques(Set estoques) {
        this.estoques = estoques;
    }
        public Set getLotes() {
        return this.lotes;
    }
    
    public void setLotes(Set lotes) {
        this.lotes = lotes;
    }




}