package br.com.threadtec.lbb.bancodados;
// Generated May 2, 2013 6:37:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Produto generated by hbm2java
 */
@Entity
@Table(name="produto",schema="public")
@NamedQueries({@NamedQuery(name="Produto.buscar_produto_id",    query="FROM Produto WHERE id = :_id"),
               @NamedQuery(name="Produto.buscar_produto_todos", query="FROM Produto")})
public class Produto  implements java.io.Serializable {


     public static final String BUSCAR_ID             = "Produto.buscar_produto_id";
     public static final String BUSCAR_TODOS          = "Produto.buscar_produto_todos";
     
     @Id
     @GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "produto_sequence")
     @SequenceGenerator(name="produto_sequence", sequenceName = "produto_sequence", allocationSize=1)
     private int id;
     @Column(name="nome", nullable=false, length=30)
     private String nome;
     @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="produto",targetEntity=Estoque.class)
     private Set estoques = new HashSet(0);

    public Produto() {
    }

	
    public Produto(int id, String nome) {
        this.id = id;
        this.nome = nome;
    }
    public Produto(int id, String nome, Set estoques) {
       this.id = id;
       this.nome = nome;
       this.estoques = estoques;
    }
   
         public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
        public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getEstoques() {
        return this.estoques;
    }
    
    public void setEstoques(Set estoques) {
        this.estoques = estoques;
    }




}


