package br.com.threadtec.lbb.bancodados;
// Generated May 2, 2013 6:37:11 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Unidade generated by hbm2java
 */
@Entity
@Table(name="unidade",schema="public")
@NamedQueries({@NamedQuery(name="Unidade.buscar_unidade_id",          query="FROM Unidade WHERE id = :_id"),
               @NamedQuery(name="Unidade.buscar_unidade_todos",       query="FROM Unidade")})
public class Unidade  implements java.io.Serializable {

     public static final String BUSCAR_ID             = "Unidade.buscar_unidade_id";
     public static final String BUSCAR_TODOS          = "Unidade.buscar_unidade_todos";
     
     @Id
     @GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "unidade_sequence")
     @SequenceGenerator(name="unidade_sequence", sequenceName = "unidade_sequence", allocationSize=1)
     private int id;
    @Column(name="descricao", nullable=false, length=10)
     private String descricao;

    public Unidade() {
    }

    public Unidade(int id, String descricao) {
       this.id = id;
       this.descricao = descricao;
    }
   
         public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
        public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


